### ISSUE TITLE
make_keras_charnet_model error

### ISSUE THREAD

**Issue by slh93** [mathDR/reading-text-in-the-wild#11]
After downloading the charnet matlab data, I am running the second step to build the json files. I have uploaded the keras tweaks to my installs however I'm still running into the following error:

AttributeError: module 'keras.backend' has no attribute 'custom_spatial_2d_padding'

This is surprising since in the backend/theano_backend.py I have the custom_spatial_2d_padding method. Any ideas why this is happening? I noticed that when I run the script, it prints out "Using TensorFlow backend." Is this expected?

Thanks!

**Comment by mathDR** [comment]
You need to be using the theano backend.  You need to install the correct versions of both tensorflow and keras

**Comment by slh93** [comment]
Yeah that makes sense. Thanks!

In the paper, they describe the CNN as being useful both for text detection and word recognition. Does this implement that or just the word recognition part? Would this work with an image with multiple words placed in the image or just images of a single word like the example images?

**Comment by mathDR** [comment]
This is ONLY the word recognition part.  The code expects a cropped text image as input.  If you give it multiple words, the dictnet won't work.  If the total length of the text is less than (I think) 22 characters, then charnet may give you good results.

**Comment by slh93** [comment]
Sorry yeah just saw that in a previous issue. Just to clarify, the only difference between charnet and dictnet is how the models are trained but the purpose of both (individual word recognition) is the same. Do you know of any other  competing text-in-the-wild solutions to the one proposed in the Jaderberg paper?

**Comment by mathDR** [comment]
In paper format?  No.  The google translate app for iOS clearly is doing this in its image functionality, so you might want to search in that space...If you just need a solution, they offer their api for it.

**Comment by slh93** [comment]
Thanks! One last thing...

I  ran into similar issues with testing charnet on the example images. I saw you had a conversation in a previous issue thread about how this wasn't broken before and that if training was done exclusively in Python, this would not be an issue:
1. Have you had any other progress since then related to what in the _preprocess method was contributing to this?
2. Is there additional info needed to train the models than what is provided in the TRAIN folder?

**Comment by mathDR** [comment]
The training was never completed (or successfully ran) in python.  I had to move on to other things so I never completed it.

As far as I know, the _preprocess method not comporting to matlab is the culprit.  If you get anything to work, please let me know!  Or better yet, submit a PR!
