### ISSUE TITLE
'TensorVariable' object has no attribute '_keras_shape'

### ISSUE THREAD

**Issue by Perseus14** [mathDR/reading-text-in-the-wild#12]
While running the code _make_keras_charnet_model.py_, I encountered the error "**'TensorVariable' object has no attribute '_keras_shape'**".

I had followed the instructions given in the README doc on overwriting _convolution.py_ and _theano_backend.py_

Apparently, the error in encountered in line 43

`model.add(Convolution2D(nb_filters[layer1], nb_conv[layer1], nb_conv[layer1],weights=weights,input_shape=(1, img_rows,img_cols),activation='relu',border_mode='same'))`

Image is attached below

![keras](https://cloud.githubusercontent.com/assets/8448630/23093765/aede2bc0-f611-11e6-9eb4-ad2367cc4f7b.png)

**Comment by Perseus14** [comment]
My keras and theano versions were different. Once I installed the required version. It worked

**Comment by mathDR** [comment]
Thanks for closing. This is what I was going to suggest.
