### ISSUE TITLE
TypeError: build() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by vj-1988** [mathDR/reading-text-in-the-wild#2]
I am getting this error when I try to execute make_keras_dictnet_model.py

```
self.build(input_shapes[0])
```

TypeError: build() takes exactly 1 argument (2 given)

**Comment by vj-1988** [comment]
This is probably because of insufficient memory. I was able to solve this by re-installing tensorflow in CPU only mode.

**Comment by mathDR** [comment]
Note:  I didn't try this on a GPU.  The one I want to run on (Jetson TK1) does not have enough memory to hold the trained network!

**Comment by vj-1988** [comment]
I have re-installed the OS after adding a TitanX. I am not getting this error now.
