### ISSUE TITLE
AttributeError: 'module' object has no attribute 'custom_spatial_2d_padding'

### ISSUE THREAD

**Issue by vj-1988** [mathDR/reading-text-in-the-wild#3]
I am getting this error when I run the make_keras_dictnet_model.py

AttributeError: 'module' object has no attribute 'custom_spatial_2d_padding'

I have copied the new files to the respective folder as mentioned in the readme. Has anyone faced the same issue before?

**Comment by Irtza** [comment]
Make sure you use the same version of Keras and Theano as shown in the readme.
building keras from source again to resolved it for me

**Comment by mathDR** [comment]
vj-1988 did Irtza's comment solve your issue?  I would like to close this.

**Comment by vj-1988** [comment]
@mathDR and @Irtza : I had to re-install my OS ( due to other reasons). Everything works fine now. Thanks.
